<a href="/product/add/" class="btn btn-info m-3">Add Movies!</a>
<a href="/product/index/" class="btn btn-info m-3">Display Movies!</a>
<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">

                <form action = "/product/update/?id=<?php echo $_GET['id'] ?>" method = 'POST'>

                 <!-- id input -->
                 <div class="form-outline mb-4">Product-ID
                        <input type="number" id="form3Example3" class="form-control form-control-lg"
                             name='id' value='<?php echo $data[0]->id  ?>' disabled/>
                    </div>

                    <!-- name input -->
                    <div class="form-outline mb-4">Product-Name
                        <input type="text" id="form3Example3" class="form-control form-control-lg"
                            name='name' value='<?php echo $data[0]->name  ?>' />
                    </div>

                    <!-- type input -->
                    <div class="form-outline mb-3">Product-Type
                        <input type="text" id="form3Example4" class="form-control form-control-lg"
                            name='type' value='<?php echo $data[0]->type  ?>' />
                    </div>

                   


                    <div class="text-center text-lg-start mt-4 pt-2">
                        <input type="submit" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;" value = 'Update Product'>

                    </div>

                </form>
            </div>
        </div>
    </div>

</section>